version: '3.9'

services:

  auth:
    container_name: auth
    build: 
      context: .
      dockerfile: docker/auth/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}:/app"
    networks:
      - auth

networks:
  auth: